version: '3.2'
services:
  postgres:
    container_name: postgres
    image: postgres:10
    restart: 'always'
    ports:
      - 5432
    environment:
      - POSTGRES_USER=ladybug
      - POSTGRES_PASSWORD=supersecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: ladybug_api
    restart: always
    build: .
    environment:
      - FLASK_ENV=docker
    depends_on:
      - postgres
    ports:
      - 5000:5000
volumes:
  pgdata:
